### PR TITLE
Update commentStart to use #

### PR DESCRIPTION
**Pull request by tonyxiao**
GraphQL comments start with # not @@

### CODE REVIEW

**Comment by rmosolgo** [comment]
Thanks for this fix! I don't know much about Atom grammars (I really struggled through this one). Can you help me understand what this is for? 

I defined comments with `#` [here](https://github.com/rmosolgo/language-graphql/blob/master/grammars/graphql.cson#L147-L149) and that seems to work inside Atom, but what is this other file for? (Somehow, I don't think I even saw it before! 😬 )

**Comment by tonyxiao** [comment]
I'm not too familiar with atom's grammer either. but this is what happens when you press `cmd + /` in the editor. Previously it would toggle the line with `@@` in front, this commit toggles it with `# ` in front.

**Comment by rmosolgo** [comment]
Ohhh it's for keyboard shortcuts! Interesting, thanks. 

> toggle the line with @@ in front

That's terrible, thanks for this fix!

**Comment by rmosolgo** [comment]
:ship: in 0.4.0!

**Pull request merged**
